name: cycIF_reg
channels:
  - simpleitk
  - conda-forge
  - defaults
dependencies:
  - simpleitk 
  - pandas 
  - numpy 
  - seaborn 
  - matplotlib 
  - scikit-learn
  - atpbar
  - pip
  - scikit-image
  - mantichora
